### ISSUE TITLE
Unable to upgrade environment for a elasticsearch service

### ISSUE THREAD

**Issue by javierav** [dokku/dokku-elasticsearch#112] opened 2022-06-30 21:14 UTC
## Description of problem

When I try to upgrade the environment vars of a ES service, I get the following error message: "Service XXX already running elasticsearch:7.16.3"

### Steps to Reproduce

```
$ dokku elasticsearch:create elastictest --image-version 7.16.3
$ dokku elasticsearch:upgrade elastictest --custom-env "ES_JAVA_OPTS=-Xms512m -Xmx512m"
```

#### Actual Results

Error message: "-----> Service elastictest already running elasticsearch:7.16.3"

#### Expected Results

Service `elastictest` should be stopped and started with the new environment vars.

**Comment by josegonzalez** [comment] 2023-02-07 10:00
The upgrade command is strictly used to upgrade from one image version to another. The flags are there to enable options to be set during the upgrade process, but otherwise do nothing.

Closing as this is working by design.

**Closed by josegonzalez** 2023-02-07 10:00 UTC

**Comment by josegonzalez** [comment] 2023-02-07 13:36
At the moment, that can be done manually by modifying the underlying files. It probably would be better to have an enhancement ticket to let folks set different values for them.
